stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/bigmartdata.csv
    outs:
    - data/raw/bigmartdata.csv


  preprocessing:
    cmd: python src/preprocessing.py --config=params.yaml
    deps:
    - src/get_data.py
    - data/raw/bigmartdata.csv
    outs:
    - data/processed/processed_bigmartdata.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/processed/processed_bigmartdata.csv
    outs:
    - data/train_test_data/train_bigmartdata.csv
    - data/train_test_data/test_bigmartdata.csv



