stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/bigmartdata.csv
    outs:
    - data/raw/bigmartdata.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/split_data.py
    - data/raw/bigmartdata.csv
    outs:
    - data/processed/train_bigmartdata.csv
    - data/processed/test_bigmartdata.csv