stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/bigmartdata.csv
    outs:
    - data/raw/bigmartdata.csv


  preprocessing:
    cmd: python src/preprocessing.py --config=params.yaml
    deps:
    - src/get_data.py
    - data/raw/bigmartdata.csv
    outs:
    - data/processed/processed_bigmartdata.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/processed/processed_bigmartdata.csv
    outs:
    - data/train_test_data/train_bigmartdata.csv
    - data/train_test_data/test_bigmartdata.csv

  train_and evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/train_test_data/train_bigmartdata.csv
    - data/train_test_data/test_bigmartdata.csv
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    - estimators.RandomForestRegressor.params.max_depth
    - estimators.RandomForestRegressor.params.max_leaf_nodes
    - estimators.RandomForestRegressor.params.min_impurity_decrease
    - estimators.RandomForestRegressor.params.n_jobs
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib




