stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/bigmartdata.csv
    outs:
    - data/raw/bigmartdata.csv


  preprocessing:
    cmd: python src/preprocessing.py --config=params.yaml
    deps:
    - src/get_data.py
    - data/raw/bigmartdata.csv
    outs:
    - data/processed/processed_bigmartdata.csv


