base:
  random_state: 42
  target_col: Item_Outlet_Sales

data_source:
  s3_source: data_given/bigmartdata.csv

load_data:
  raw_dataset_csv: data/raw/bigmartdata.csv

preprocessing:
  processed_data_path: data/processed/processed_bigmartdata.csv

split_data:
  train_path: data/train_test_data/train_bigmartdata.csv
  test_path : data/train_test_data/test_bigmartdata.csv
  test_size : 0.2

estimators:
  LinearRegression:
    params:
      l1_ratio: 0.9

model_dir: saved_models
