base:
  random_state: 42
  target_col: item_outlet_sales

data_source:
  s3_source: data_given/bigmartdata.csv

load_data:
  raw_dataset_csv: data/raw/bigmartdata.csv

preprocessing:
  processed_data_path: data/processed/processed_bigmartdata.csv

split_data:
  train_path: data/train_test_data/train_bigmartdata.csv
  test_path : data/train_test_data/test_bigmartdata.csv
  test_size : 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 100
      max_depth: 7
      max_leaf_nodes: None
      min_impurity_decrease: 0.0
      n_jobs: None



model_dir: saved_models


reports:
  params: report/params.json
  scores: report/scores.json
